definitions:
  dto.LoginUserRequest:
    properties:
      email:
        type: string
      password:
        type: string
    type: object
  dto.NoteCreateRequest:
    properties:
      content:
        type: string
      title:
        type: string
    type: object
  dto.NoteUpdateRequest:
    properties:
      content:
        type: string
      id:
        type: string
      title:
        type: string
    type: object
  dto.RegisterUserRequest:
    properties:
      email:
        type: string
      password:
        type: string
      username:
        type: string
    type: object
info:
  contact: {}
paths:
  /notes/{id}:
    get:
      parameters:
      - description: Note ID
        in: path
        name: id
        required: true
        type: string
      responses: {}
      security:
      - ApiKeyAuth: []
      tags:
      - Notes
  /notes/create:
    post:
      parameters:
      - description: Create note payload
        in: body
        name: body
        required: true
        schema:
          $ref: '#/definitions/dto.NoteCreateRequest'
      responses: {}
      security:
      - ApiKeyAuth: []
      tags:
      - Notes
  /notes/delete/{id}:
    delete:
      parameters:
      - description: Note ID
        in: path
        name: id
        required: true
        type: string
      responses: {}
      security:
      - ApiKeyAuth: []
      tags:
      - Notes
  /notes/pagination:
    get:
      parameters:
      - description: Page number
        in: query
        name: page
        required: true
        type: integer
      responses: {}
      security:
      - ApiKeyAuth: []
      tags:
      - Notes
  /notes/update:
    put:
      parameters:
      - description: Update note payload
        in: body
        name: body
        required: true
        schema:
          $ref: '#/definitions/dto.NoteUpdateRequest'
      responses: {}
      security:
      - ApiKeyAuth: []
      tags:
      - Notes
  /users/login:
    post:
      parameters:
      - description: Login payload
        in: body
        name: body
        required: true
        schema:
          $ref: '#/definitions/dto.LoginUserRequest'
      responses: {}
      tags:
      - Users
  /users/register:
    post:
      parameters:
      - description: Register payload
        in: body
        name: body
        required: true
        schema:
          $ref: '#/definitions/dto.RegisterUserRequest'
      responses: {}
      tags:
      - Users
securityDefinitions:
  ApiKeyAuth:
    in: header
    name: Authorization
    type: apiKey
swagger: "2.0"
